import os

AZURE_CLIENT_ID =  os.environ["AZURE_CLIENT_ID"] 

AZURE_TENANT_ID = os.environ["AZURE_TENANT_ID"]

AZURE_CLIENT_SECRET = os.environ["AZURE_CLIENT_SECRET"]

AZURE_SUBSCRIPTION_ID = os.environ["AZURE_SUBSCRIPTION_ID"]

AZURE_RESOURCE_GROUP_NAME = os.environ["AZURE_RESOURCE_GROUP_NAME"]

AZURE_DATA_FACTORY_NAME = os.environ["AZURE_DATA_FACTORY_NAME"]

AZURE_STORAGE_ACCOUNT = os.environ["AZURE_STORAGE_ACCOUNT"]

AZURE_CONTAINER_NAME = os.environ["AZURE_CONTAINER_NAME"]

OUTPUT_FILE_NAME = "pipeline-lineage.json"

if "OUTPUT_FILE_NAME" in os.environ:
    OUTPUT_FILE_NAME = os.environ["OUTPUT_FILE_NAME"]
